CREATE TABLE OPT_DiceTypes (
   DiceType_Id INT PRIMARY KEY AUTO_INCREMENT,
   DiceType VARCHAR(5) UNIQUE NOT NULL,
   DiceType_MaxPossibleValue INT NOT NULL
);

CREATE TABLE OPT_MagicSchools (
   MagicSchool_Id INT PRIMARY KEY AUTO_INCREMENT,
   MagicSchool VARCHAR(30) UNIQUE NOT NULL
)

CREATE TABLE OPT_DamageTypes (
   DamageType_Id INT PRIMARY KEY AUTO_INCREMENT,
   DamageType VARCHAR(20) UNIQUE NOT NULL
)
